import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Боковое меню строится автоматически из структуры папок docs/
// Порядок задаётся полем sidebar_position во frontmatter и _category_.json.
const sidebars: SidebarsConfig = {
  roadmapSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
